[2024-12-20T23:37:23.247+0000] {processor.py:186} INFO - Started process (PID=1717) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:37:23.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:37:23.253+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:23.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:37:23.312+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:23.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 4, in <module>
    from django.utils.dateparse import parse_datetime
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:37:23.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:37:23.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.148 seconds
[2024-12-20T23:37:56.005+0000] {processor.py:186} INFO - Started process (PID=1781) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:37:56.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:37:56.010+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:56.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:37:56.051+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:56.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 4, in <module>
    from django.utils.dateparse import parse_datetime
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:37:56.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:37:56.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.217 seconds
[2024-12-20T23:38:27.478+0000] {processor.py:186} INFO - Started process (PID=1847) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:38:27.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:38:27.488+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:27.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:38:27.572+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:27.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 4, in <module>
    from django.utils.dateparse import parse_datetime
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:38:27.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:38:28.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.447 seconds
[2024-12-20T23:39:00.103+0000] {processor.py:186} INFO - Started process (PID=1913) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:39:00.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:39:00.118+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:00.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:39:00.177+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:00.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 4, in <module>
    from django.utils.dateparse import parse_datetime
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:39:00.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:39:00.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.184 seconds
[2024-12-20T23:39:36.792+0000] {processor.py:186} INFO - Started process (PID=1980) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:39:36.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:39:36.797+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:36.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:39:36.829+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:36.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 4, in <module>
    from django.utils.dateparse import parse_datetime
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:39:36.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:39:37.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.005 seconds
[2024-12-20T23:40:08.337+0000] {processor.py:186} INFO - Started process (PID=2047) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:08.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:40:08.343+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:08.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:09.026+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:08.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 4, in <module>
    from django.utils.dateparse import parse_datetime
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:40:09.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:09.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.813 seconds
[2024-12-20T23:40:39.768+0000] {processor.py:186} INFO - Started process (PID=2112) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:39.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:40:39.772+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:39.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:39.809+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:39.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 4, in <module>
    from django.utils.dateparse import parse_datetime
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:40:39.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:39.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.094 seconds
[2024-12-20T23:40:53.307+0000] {processor.py:186} INFO - Started process (PID=2145) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:53.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:40:53.312+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:53.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:53.341+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:53.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:40:53.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:40:54.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.057 seconds
[2024-12-20T23:41:25.901+0000] {processor.py:186} INFO - Started process (PID=2212) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:41:25.905+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:41:25.911+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:25.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:41:25.977+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:25.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:41:25.990+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:41:26.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.983 seconds
[2024-12-20T23:41:58.237+0000] {processor.py:186} INFO - Started process (PID=2277) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:41:58.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:41:58.343+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:58.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:41:58.418+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:58.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:41:58.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:41:58.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.368 seconds
[2024-12-20T23:42:28.853+0000] {processor.py:186} INFO - Started process (PID=2343) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:42:28.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:42:28.857+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:28.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:42:28.889+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:28.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:42:28.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:42:29.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.983 seconds
[2024-12-20T23:43:04.065+0000] {processor.py:186} INFO - Started process (PID=2408) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:43:04.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:43:04.071+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:04.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:43:04.113+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:04.110+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:43:04.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:43:04.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.108 seconds
[2024-12-20T23:43:35.218+0000] {processor.py:186} INFO - Started process (PID=2473) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:43:35.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:43:35.225+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:35.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:43:35.263+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:35.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:43:35.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:43:36.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.014 seconds
[2024-12-20T23:44:06.415+0000] {processor.py:186} INFO - Started process (PID=2540) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:06.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:44:06.441+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:06.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:06.488+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:06.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:44:06.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:06.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.156 seconds
[2024-12-20T23:44:15.320+0000] {processor.py:186} INFO - Started process (PID=2554) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:15.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:44:15.326+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:15.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:15.467+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:15.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:44:15.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:15.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.218 seconds
[2024-12-20T23:44:45.646+0000] {processor.py:186} INFO - Started process (PID=2620) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:45.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:44:45.662+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:45.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:45.694+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:45.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:44:45.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:44:45.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.117 seconds
[2024-12-20T23:45:16.489+0000] {processor.py:186} INFO - Started process (PID=2688) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:45:16.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:45:16.494+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:16.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:45:16.573+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:16.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 5
    sys.path.append('C:\Users\yara\Desktop\airflow task\simulator_project\simulator')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-12-20T23:45:16.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:45:16.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.192 seconds
[2024-12-20T23:45:37.558+0000] {processor.py:186} INFO - Started process (PID=2728) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:45:37.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:45:37.564+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:37.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:45:37.643+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:37.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:45:37.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:45:37.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.159 seconds
[2024-12-20T23:46:09.492+0000] {processor.py:186} INFO - Started process (PID=2791) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:46:09.495+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:46:09.502+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:09.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:46:09.641+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:09.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:46:09.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:46:10.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.922 seconds
[2024-12-20T23:46:41.086+0000] {processor.py:186} INFO - Started process (PID=2857) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:46:41.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:46:41.096+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:41.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:46:41.130+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:41.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:46:41.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:46:41.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.118 seconds
[2024-12-20T23:47:12.191+0000] {processor.py:186} INFO - Started process (PID=2919) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:47:12.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:47:12.196+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:12.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:47:12.226+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:12.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:47:12.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:47:13.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.059 seconds
[2024-12-20T23:47:44.580+0000] {processor.py:186} INFO - Started process (PID=2971) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:47:44.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:47:44.588+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:44.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:47:44.656+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:44.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:47:44.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:47:45.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.010 seconds
[2024-12-20T23:48:17.405+0000] {processor.py:186} INFO - Started process (PID=3037) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:48:17.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:48:17.417+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:17.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:48:17.505+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:17.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:48:17.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:48:18.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.255 seconds
[2024-12-20T23:48:49.667+0000] {processor.py:186} INFO - Started process (PID=3103) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:48:49.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:48:49.686+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:49.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:48:49.826+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:49.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:48:49.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:48:50.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.148 seconds
[2024-12-20T23:49:24.718+0000] {processor.py:186} INFO - Started process (PID=3170) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:24.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:49:24.724+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:24.723+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:24.766+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:24.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:49:24.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:25.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.088 seconds
[2024-12-20T23:49:42.855+0000] {processor.py:186} INFO - Started process (PID=3214) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:42.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:49:42.861+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:42.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:42.925+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:42.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:49:42.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:42.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.128 seconds
[2024-12-20T23:49:50.344+0000] {processor.py:186} INFO - Started process (PID=3226) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:50.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:49:50.351+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:50.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:50.409+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:50.399+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:49:50.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:49:52.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.047 seconds
[2024-12-20T23:50:19.639+0000] {processor.py:186} INFO - Started process (PID=3291) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:50:19.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:50:19.644+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:19.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:50:19.692+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:19.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:50:19.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:50:19.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.114 seconds
[2024-12-20T23:50:56.271+0000] {processor.py:186} INFO - Started process (PID=3356) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:50:56.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:50:56.278+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:56.277+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:50:56.339+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:56.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:50:56.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:50:56.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.721 seconds
[2024-12-20T23:51:29.645+0000] {processor.py:186} INFO - Started process (PID=3416) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:51:29.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:51:29.658+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:29.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:51:29.734+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:29.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:51:29.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:51:29.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.170 seconds
[2024-12-20T23:52:00.181+0000] {processor.py:186} INFO - Started process (PID=3480) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:52:00.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:52:00.192+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:00.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:52:00.237+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:00.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:52:00.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:52:00.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.145 seconds
[2024-12-20T23:52:30.490+0000] {processor.py:186} INFO - Started process (PID=3544) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:52:30.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:52:30.500+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:30.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:52:30.528+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:30.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:52:30.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:52:31.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.117 seconds
[2024-12-20T23:53:02.589+0000] {processor.py:186} INFO - Started process (PID=3611) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:53:02.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:53:02.598+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:02.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:53:02.640+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:02.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 7, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:53:02.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:53:02.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.134 seconds
[2024-12-20T23:53:29.784+0000] {processor.py:186} INFO - Started process (PID=3669) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:53:29.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:53:29.792+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:29.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:53:29.838+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:29.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 11, in <module>
    import django
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:53:29.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:53:29.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.109 seconds
[2024-12-20T23:54:03.710+0000] {processor.py:186} INFO - Started process (PID=3731) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:54:03.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:54:03.725+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:54:03.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:54:04.695+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:54:04.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 11, in <module>
    import django
ModuleNotFoundError: No module named 'django'
[2024-12-20T23:54:04.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:54:04.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 1.165 seconds
[2024-12-20T23:54:16.757+0000] {processor.py:186} INFO - Started process (PID=3762) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:54:16.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:54:16.762+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:54:16.762+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:54:16.832+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:54:16.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 8, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:54:16.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:54:16.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.172 seconds
[2024-12-20T23:56:55.801+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:56:55.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:56:55.833+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:56:55.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:56:55.888+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:56:55.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 8, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:56:55.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:56:55.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.194 seconds
[2024-12-20T23:57:26.643+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:57:26.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/generate_simulator_dags.py for tasks to queue
[2024-12-20T23:57:26.652+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:57:26.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:57:26.696+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:57:26.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/generate_simulator_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/generate_simulator_dags.py", line 8, in <module>
    from simulator.models import Simulator
ModuleNotFoundError: No module named 'simulator'
[2024-12-20T23:57:26.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/generate_simulator_dags.py
[2024-12-20T23:57:26.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/generate_simulator_dags.py took 0.137 seconds
